### ISSUE TITLE
Issue when running acquisition

### ISSUE THREAD

**Issue by trungtindinh** [a-rouxel/simca#3]
Hello,
In the Acquisition step, when clicking on "Run Acquisition", I received the following error message: 
`Traceback (most recent call last):`
 `File "/simca/gui_elements/AcquisitionWidget.py", line 208, in run
    self.cassi_system.image_acquisition(use_psf=self.acquisition_config["psf"]["use_psf"],chunck_size=50)`
 `File "/simca/simca/CassiSystem.py", line 289, in image_acquisition
    scene = match_dataset_to_instrument(dataset, self.filtering_cube)`
 `File "/simca/simca/functions_acquisition.py", line 97, in match_dataset_to_instrument
    return scene`
`UnboundLocalError: local variable 'scene' referenced before assignment`

Could you verify this error?
Thank you.

**Comment by a-rouxel** [comment]
Hello,
The error you are referring was appearing when the size of your scene, spatially and spectrally, was exactly the one of your filtering cube (which is quite unusual, we usually have all kinds of problems haha). Anyway I fixed this issue and added print statements. Please tell me if you still have issues
